---
name: ci

on:
  push:
    branches: [add-github-actions]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        puppet_version: [6, 7]

    name: Check / Puppet ${{ matrix.puppet_version }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run pdk validate
        uses: puppets-epic-show-theatre/action-pdk-validate@v1
        with:
          puppet-version: ${{ matrix.puppet_version }}
          pdk-image: "puppet/pdk:2.2.0.0"

      - name: Run pdk test unit
        uses: puppets-epic-show-theatre/action-pdk-test-unit@v1
        with:
          puppet-version: ${{ matrix.puppet_version }}
          pdk-image: "puppet/pdk:2.2.0.0"

  acceptance:
      strategy:
        fail-fast: false
        matrix:
          os: ['el', 'ub', 'deb', 'deb']
          puppet_version: [6, 7]

      name: Acceptance / ${{ matrix.os }} / Puppet ${{ matrix.puppet_version }}
      runs-on: ubuntu-20.04
      needs:
        - check

      steps:
        - name: Checkout source
          uses: actions/checkout@v3

        - name: Setup Ruby
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: "2.7"
            bundler-cache: true

        - name: Run Litmus
          env:
            DEBUG: true
          run: |
            bundle exec rake 'litmus:provision_list[litmus_${{ matrix.os }}]'
            bundle exec rake 'litmus:install_agent[puppet${{ matrix.puppet_version }}]'
            bundle exec rake litmus:install_module
            bundle exec rake litmus:acceptance:parallel
        - name: Cleanup
          run: |
            bundle exec rake 'litmus:tear_down'
